### ISSUE TITLE
Mapping Informa target families to GO terms

### ISSUE THREAD

**Issue by eric-czech** [AbbVie-ComputationalGenomics/genetic-evidence-approval#1]
Hello, thank you for sharing this codebase!

In attempting to understand the derivation of certain variables used in the stan model, I came across this description of the process for generating target family indicator fields (in supplement 5):

> GO Annotation Previous work has shown differences in success probability among target classes (e.g. kinases and GPCR) [6]. Pharmaprojects provides functional annotations which seemed to be predictive of success, but were not available for all targets. We translated these annotations to Gene Ontology (GO) [1][2] terms when possible, found all descendants of these terms using the goatools Python module [4], and then annotated each gene target with a term if it was annotated with that term or a descendant term. GO term annotations were obtained using biomaRt [7]. S21 Fig shows variation in approval and GWAS links by target class.

Is the mapping of PharmaProjects target annotations to GO terms used for this available anywhere?

Thanks.

**Comment by emilyking** [comment]
Sorry, we don't have this in the files that we released.

**Comment by eric-czech** [comment]
Ok @emilyking, I have a couple follow up questions if you don't mind.  Do you have any idea how some of the following target family assignments might have been made?  I'm trying to reproduce what was provided in [Target_Properties.tsv](https://github.com/AbbVie-ComputationalGenomics/genetic-evidence-approval/blob/master/data/Target_Properties.tsv) but I'm at a loss in a number of cases like this:

1. **GHRHR** (ENSG00000106128)
    - This was assigned the features "GO G-protein coupled receptor activity" and "GO chemokine receptor activity" in Target_Properties.tsv
    - The GO annotations according to Ensembl ([ENSG00000106128](https://useast.ensembl.org/Homo_sapiens/Gene/Ontologies/molecular_function?g=ENSG00000106128;r=2:48686774-48755730)) don't show [chemokine receptor activity](https://www.ebi.ac.uk/ols/ontologies/cco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0004950)
    - The associated PharmaProjects target family is simply "Receptor > GPCR"
2. **CALCRL** (ENSG00000064989)
    - This was assigned the following features in Target_Properties.tsv:
        - GO G-protein coupled receptor activity
        - GO transport
        - GO cannabinoid receptor activity
    - The GO annotations according to Ensembl ([ENSG00000064989](http://useast.ensembl.org/Homo_sapiens/Gene/Ontologies/molecular_function?db=core;g=ENSG00000064989;r=2:187341964-187448460)) don't show [transport](https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0044765) or [cannabinoid receptor activity](https://www.ebi.ac.uk/ols/ontologies/cco/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0004949)
    - The associated PharmaProjects target family is again only "Receptor > GPCR" 
3. **NTSR1** (ENSG00000101188)
    - This was assigned the features "GO G-protein coupled receptor activity" and "GO prostanoid receptor activity" in Target_Properties.tsv
    - There are no reported target families for this in PharmaProjects
    - Like the above cases, I cannot find evidence of why the non-GPCR term "prostanoid receptor activity" would be associated

I can imagine that Informa may have changed target families and some GO terms have potentially become obsolete (not any in the examples above though to my knowledge) since this original analysis was run, but I am seeing enough discrepancies like this that I wanted to be sure there wasn't more to how the mapping was done.  To that end:

1. What was biomaRt used for?  Was it just to aid in mapping the Informa families to GO terms?
2. Did you consider using any other sources of target family associations like this or do you believe Informa captures this relationship as well or better than anything else?
3. Were any of the target -> family associations made by hand or through other sources?

Thanks again!

**Comment by emilyking** [comment]
1. Correct
2. Probably other sources could be used, I liked Informa because it had a relatively small # of terms chosen to be relevant to drug discovery.
3. No

I looked into your first example, I agree that it should not have annotation chemokine receptor activity.
