### ISSUE TITLE
target_indication.tsv: First Added column documentation

### ISSUE THREAD

**Issue by dhimmel** [AbbVie-ComputationalGenomics/genetic-evidence-approval#2]
[target_indication.tsv](https://github.com/AbbVie-ComputationalGenomics/genetic-evidence-approval/blob/3a5eae74ccc097e1c9f18b989c44daca3f4e3b1c/data/target_indication.tsv) includes a `First.Added` column. Here's the first rows for context:

| MSH | ensembl_id | lApprovedUS.EU | Phase.Latest | First.Added | Inactive | symbol |
|-|-|-|-|-|-|-|
| Abortion, Spontaneous | ENSG00000119535 | FALSE | unknown | NA | TRUE | CSF3R |
| Acidosis | ENSG00000151617 | FALSE | Phase I Clinical Trial | 2012-10-27 | FALSE | EDNRA |
| Acne Vulgaris | ENSG00000012779 | FALSE | Phase II Clinical Trial | NA | TRUE | ALOX5 |
| Acne Vulgaris | ENSG00000026508 | FALSE | Approved | NA | FALSE | CD44 |
| Acne Vulgaris | ENSG00000057252 | FALSE | unknown | 2009-07-01 | TRUE | SOAT1 |

The [README](https://github.com/AbbVie-ComputationalGenomics/genetic-evidence-approval/blob/3a5eae74ccc097e1c9f18b989c44daca3f4e3b1c/README.md#target_indicationtsv) documents this as:

> First Added = earliest added date for any drug with this target and indication.

Is this the same metric that the [manuscript](https://doi.org/10.1371/journal.pgen.1008489) refers to as "Earliest date in the Pharmaprojects event history" or "first recorded drug event"? This was my initial understanding, but the readme makes it sounds like `First.Added` might be when the Pharmaprojects drug record was created rather than when the first event for a drug is dated.

BTW thanks for the documentation and code & data sharing that accompanying this study!

**Comment by emilyking** [comment]
I can clarify this.  Usually the event history contains an event called "New Product" which is also the earliest date in the event history (there are a few exceptions).  This is the event I used.

**Comment by dhimmel** [comment]
Looking at the current [Pharmaprojects Glossary](https://citeline.zendesk.com/hc/en-us/articles/360008401514-Pharmaprojects-Glossary) (login-walled), I don't see an event history for "New Product", but do see one for "Drug Added", which is defined as:

> Drug Added - Applied when a new drug is added to Pharmaprojects. The event details will show the phase of development the drug was at when it was added.

Perhaps "Drug Added" is the event you used to calculate `First.Added`?

Using Pharmaprojects from 2020-08-31 and defining two variables for each drug:

1. `first_event_date`: earliest keyEventDate for all of a drug's events
2. `drug_added_date`: earliest keyEventDate where `keyEventHistory == "Drug Added"` (presumably the same as `First.Added`)

In total, Pharmaprojects had 159,306 drug records. 77,465 of these drug records had at least one keyEvent, such that a `first_event_date` could be calculated. Of those, 6,889 were missing a "Drug Added" event and 1,584 had a `drug_added_date` that was later than its `first_event_date`. So 11% of drugs with events are effected by using drug added versus earliest date of any event.

For the 1,584 drugs where drug_added_date > first_event_date, here is a histogram of difference in years:

![image](https://user-images.githubusercontent.com/1117703/104761125-6cc79d00-5730-11eb-9dc5-83aad9c3c0a4.png)

So nothing that in most cases, the lag from first_event_date to drug_added_date is less than a year, but are a few hundred drugs where the lag exceeds a year and can be as long as 30 years.

I could see an argument for using earliest date in subsequent analyses (`first_event_date` rather than `drug_added_date`), since it is more complete and might better assess when development on a drug commences as opposed to when Pharmaprojects adds a drug record. Do you remember any reasons why you chose `drug_added_date` over `first_event_date`?

From the manuscript:

> S7 Fig. First event date in Pharmaprojects by development status. Earliest date in the Pharmaprojects event history by status

This sounds more like first_event_date rather than drug_added_date. Is `First.Added` computed separately from the drug date plotted in S7 fig?

Thanks in advance for helping me understand this rather specific and esoteric question!

**Comment by dhimmel** [comment]
Looking at first_event_date for each drug, here is the corresponding keyEventHistory value (i.e. which keyEventHistory value appears first for every drug):

```
Drug Added                              68398
No Development Reported                  2246
Discontinuation Confirmed                1137
New Licensing Opportunity                 948
Orphan Drug Status Granted                834
Global Status Advance                     706
New Licensee                              480
Chemical Structure Reported               415
New Patent                                267
Development Suspended                     236
First Approval                            225
New Launch                                200
New Approval                              197
First Launch                              189
First Filing                              141
Nonproprietary Name Granted               133
License Discontinued                      128
Lead Identified                           108
New Disease                                92
Development Restarted                      87
IND Filing                                 73
Novel Target Identified                    53
New Mechanism                              35
New Therapeutic Class                      34
Withdrawn from Market                      29
Change in Licensee Status                  25
Expedited Review Designation Granted       14
New Target                                 12
Disease Phase Change                       10
New Filing                                  8
Global Status Reversion                     4
Supplemental Filing                         1
```

**Comment by emilyking** [comment]
It's hard for me to answer this for sure as I don't currently have Pharmaprojects access, but I think what you have as "Drug Added" has pretty much the same behavior as what was called "New Product" in the dataset I was working with.  They may have changed what this event is called.

**Comment by dhimmel** [comment]
Thanks @emilyking for your recollection.

Will close this since I'm not sure there is anything more to do here. If I see "New Product" in historical Pharmaproject snapshots or docs, I'll drop a note here.
